plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.kapt'
}

group = 'io.karpfen'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':karpfen-dsl-tools')

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.json:json:20240303'

    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    kapt 'com.google.auto.service:auto-service:1.1.1'

    // Testing
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test'
    testImplementation 'io.mockk:mockk:1.14.11'

    testCompileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    kaptTest 'com.google.auto.service:auto-service:1.1.1'
}

kotlin {
    jvmToolchain(21)
}

test {
    useJUnitPlatform()
}