import kotlinx.benchmark.gradle.BenchmarkConfiguration
import kotlinx.benchmark.gradle.BenchmarkTarget

plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.kapt'
    id 'org.jetbrains.kotlinx.benchmark' version '0.4.13'
    id 'org.jetbrains.kotlin.plugin.allopen' version "2.2.0"
}

group = 'io.karpfen'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':karpfen-dsl-tools')

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.json:json:20240303'

    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    kapt 'com.google.auto.service:auto-service:1.1.1'

    // Testing
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test'
    testImplementation 'io.mockk:mockk:1.14.11'

    testCompileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    kaptTest 'com.google.auto.service:auto-service:1.1.1'

    implementation 'org.jetbrains.kotlinx:kotlinx-benchmark-runtime:0.4.13'
}

allOpen {
    //noinspection GroovyAssignabilityCheck
    annotation('org.openjdk.jmh.annotations.State')
}

kotlin {
    jvmToolchain(21)
    target {
        compilations.create("benchmark")
                .associateWith(compilations.named("main").get())
    }
}

benchmark.targets.register("benchmark")



test {
    useJUnitPlatform()
}